### PR TITLE
Add Pytorch Sample

### PR DESCRIPTION
**Pull request by chengyaox**
This sample gets ideas from the [SGX-LKL ML Sample](https://github.com/lsds/sgx-lkl/tree/oe_port/samples/ml/pytorch).

I test on my device with SIM mode and it works.

The run_pytorch_on_occlum.sh script is modified from the python example. In Step 2. Copy files into Occlum Workspace and build.

I removed some unnecessary library and it worked for this sample training script.

With more complex PyTorch samples, it may require more libraries to copy into Occlum Workspace. Since I am a beginner at Pytorch, it is hard for me to find out all PyTorch dependency.

Hopes this sample can help.

### CODE REVIEW

**Comment by tatetian** [comment]
Hi @chengyaox , thanks a lot for the PR. Personally, I consider PyTroch at the top of my wish list for demo. So I really appreciate that you took the efforts to make this demo. We will give you review feedbacks in the next week. Thanks again.

**Comment by guzongmin** [comment]
I am very appreciate you to provide this PR for Occlum. This is really what we need, good job.

My comments are:
+ There is a docker file used to copy PyTorch into Occlum execution environment. If we could use docker multistage build, it is better ([https://docs.docker.com/develop/develop-images/multistage-build/](https://docs.docker.com/develop/develop-images/multistage-build/)). We could copy the PyTorch binaries in stage 1 and run the occlum PyTorch sample in stage 2.
+ In order to keep the demo working in each commit, we could add the demo into the CI test list. [This](https://github.com/occlum/occlum/blob/master/docs/demo_contribution_guide.md) is the guide to help you integrate the demo into Occlum demo. 
+ Can you please merge your commits into a single commit with a meaningful commit message? For example "Add PyTorch demo".

**Comment by chengyaox** [comment]
> I am very appreciate you to provide this PR for Occlum. This is really what we need, good job.
> 
> My comments are:
> 
> * There is a docker file used to copy PyTorch into Occlum execution environment. If we could use docker multistage build, it is better (https://docs.docker.com/develop/develop-images/multistage-build/). We could copy the PyTorch binaries in stage 1 and run the occlum PyTorch sample in stage 2.
> * In order to keep the demo working in each commit, we could add the demo into the CI test list. [This](https://github.com/occlum/occlum/blob/master/docs/demo_contribution_guide.md) is the guide to help you integrate the demo into Occlum demo.
> * Can you please merge your commits into a single commit with a meaningful commit message? For example "Add PyTorch demo".

**Comment by chengyaox** [comment]
> I am very appreciate you to provide this PR for Occlum. This is really what we need, good job.
> 
> My comments are:
> 
> * There is a docker file used to copy PyTorch into Occlum execution environment. If we could use docker multistage build, it is better (https://docs.docker.com/develop/develop-images/multistage-build/). We could copy the PyTorch binaries in stage 1 and run the occlum PyTorch sample in stage 2.
> * In order to keep the demo working in each commit, we could add the demo into the CI test list. [This](https://github.com/occlum/occlum/blob/master/docs/demo_contribution_guide.md) is the guide to help you integrate the demo into Occlum demo.
> * Can you please merge your commits into a single commit with a meaningful commit message? For example "Add PyTorch demo".

I have merged the commits into a single one, I will try to work on recommendations 1 and 2 later. Thanks for the recogition.

**Pull request closed without merging**
