### PR TITLE
Bash

### PR DESCRIPTION
**Pull request by qzheng527**

### CODE REVIEW

**Review by guzongmin — COMMENTED** [review]
We could add two bom files to help user import the bash into their project.

**Review by guzongmin — COMMENTED** [review]
Dockerfile.aliyunlinux2, Dockerfile.centos7.5 and Dockerfile.centos8.1 are not supported. So we do not need to change them.  Maybe we should remove those files in a separate PR.

**Comment by qzheng527** [comment]
> We could add two bom files to help user import the bash into their project.

Yes, we can do that after this PR got merged.
With the PR merged, the new docker image with prebuilt bash would be pushed to docker hub.
Then the new bom files could be used in the new bash demo.

**Comment by qzheng527** [comment]
> Dockerfile.aliyunlinux2, Dockerfile.centos7.5 and Dockerfile.centos8.1 are not supported. So we do not need to change them. Maybe we should remove those files in a separate PR.

Ok, I will update this PR and create a new PR to remove Dockerfile.centos7.5 and Dockerfile.centos8.1

**Review by guzongmin — APPROVED** [review]
LGTM

**Pull request merged**
